#!/bin/bash
INSTALL_PATH=/home/vagrant/apps
zk(){
    usage="Usage: $0 (start|stop|status)"
 
    if [ $# -lt 1 ]; then
        echo $usage
        exit 1
    fi
    case $1 in
        start)
            for i in {"hdp101","hdp102","hdp103"};
            do
                echo "-----$1 $i zookeeper-------"
                ssh $i "source /etc/profile;$INSTALL_PATH/zookeeper/bin/zkServer.sh start"
            done
            ;;
        stop)
            for i in {"hdp101","hdp102","hdp103"};
            do
                echo "------$1 $i zookeeper-------"
                ssh $i "source /etc/profile;$INSTALL_PATH/zookeeper/bin/zkServer.sh stop"
            done
            ;;
        status)
            for i in {"hdp101","hdp102","hdp103"};
            do
                echo "------$i status-------"
                ssh $i "source /etc/profile;$INSTALL_PATH/zookeeper/bin/zkServer.sh status"
            done
            ;;
        *)
            echo $usage
            ;;
    esac
}
#一键启动集群
kafka(){
    usage="Usage: $0 (start|stop)"
 
    if [ $# -lt 1 ]; then
        echo $usage
        exit 1
    fi
    case $1 in
        start)
            SIGNAL=${SIGNAL:-TERM}
            PIDS=$(ps ax | grep java | grep -i QuorumPeerMain | grep -v grep | awk '{print $1}')

            if [ -z "$PIDS" ]; then
                echo "Success to start zookeeper."
                zk start 
                echo "-----$1 $i start-------"
            else
                echo "Zookeeper has been started"
            fi
            for i in {"hdp101","hdp102","hdp103"};
            do
                echo "-----$1 $i kafka-------"
                ssh $i "source /etc/profile;$INSTALL_PATH/kafka/bin/kafka-server-start.sh -daemon $INSTALL_PATH/kafka/config/server.properties"
            done
            ;;
        stop)
            for j in {"hdp101","hdp102","hdp103"};
            do
                echo "-----$1 $j kafka-------"
                ssh $j  "kill -9 \$(ps ax |grep -i 'Kafka'| grep java| grep -v grep| awk '{print \$1}')"
            done
            ;;
        *)
            echo $usage
            ;;
    esac
}
dfs(){
    usage="Usage: $0 (start|stop)"
 
    if [ $# -lt 1 ]; then
        echo $usage
        exit 1
    fi
    case $1 in
        start)
            sh $INSTALL_PATH/hadoop/sbin/start-dfs.sh
            ;;
        stop)
            sh $INSTALL_PATH/hadoop/sbin/stop-dfs.sh
            ;;
        *)
            echo $usage
            ;;
    esac
}
yarn(){
    usage="Usage: $0 (start|stop)"
 
    if [ $# -lt 1 ]; then
        echo $usage
        exit 1
    fi
    case $1 in
        start)
            sh $INSTALL_PATH/hadoop/sbin/start-yarn.sh
            ;;
        stop)
            sh $INSTALL_PATH/hadoop/sbin/stop-yarn.sh
            ;;
        *)
            echo $usage
            ;;
    esac
}
spark(){
    usage="Usage(spark): $0 (start|stop)"
 
    if [ $# -lt 1 ]; then
        echo $usage
        exit 1
    fi
    case $1 in
        start)
            sh $INSTALL_PATH/spark/sbin/start-all.sh
            ;;
        stop)
            sh $INSTALL_PATH/spark/sbin/stop-all.sh
            ;;
        *)
            echo $usage
            ;;
    esac
}
flink(){
    usage="Usage(flink): $0 (start|stop)"
 
    if [ $# -lt 1 ]; then
        echo $usage
        exit 1
    fi
    case $1 in
        start)
            $INSTALL_PATH/flink/bin/start-cluster.sh
            ;;
        stop)
            $INSTALL_PATH/flink/bin/stop-cluster.sh
            ;;
        *)
            echo $usage
            ;;
    esac
}
hbase(){
    usage="Usage(hbase): $0 (start|stop)"
 
    if [ $# -lt 1 ]; then
        echo $usage
        exit 1
    fi
    case $1 in
        start)
            $INSTALL_PATH/hbase/bin/start-hbase.sh
            ;;
        stop)
            $INSTALL_PATH/hbase/bin/stop-hbase.sh
            ;;
        *)
            echo $usage
            ;;
    esac
}

kibana(){
    usage="Usage: $0 (start|stop)"

    if [ $# -lt 1 ]; then
        echo $usage
        exit 1
    fi
    case $1 in
        start)
            nohup ${INSTALL_PATH}/kibana/bin/kibana > ${INSTALL_PATH}/kibana/logs/kibana.log 2>&1 &
            ;;
        stop)
            #ps -ef |grep kibana |grep -v grep |awk '{print $2}' |xargs kill
            kill -9 $(ps -ef |grep kibana| grep -v grep| awk '{print $2}')
            ;;
        *)
            echo $usage
            ;;
    esac
}

elasticsearch(){
    usage="Usage: $0 (start|stop|restart)"

    if [ $# -lt 1 ]; then
        echo $usage
        exit 1
    fi
    case $1 in
        start)
            for i in {"hdp101","hdp102","hdp103"};
            do
                echo "-----$1 $i elasticsearch-------"
                ssh $i "source /etc/profile;$INSTALL_PATH/elasticsearch/bin/elasticsearch -d -p pid"
            done
            kibana start
            ;;
        stop)
            for j in {"hdp101","hdp102","hdp103"};
            do
                echo "-----$1 $j elasticsearch-------"
                ssh $j  "kill -9 \$(ps ax |grep -i 'elasticsearch'| grep java| grep -v grep| awk '{print \$1}')"
            done
            kibana stop
            ;;
        restart)
            elasticsearch stop
            elasticsearch start
            ;;
        *)
            echo $usage
            ;;
    esac
}

redis(){
#redis服务器监听的端口
REDISPORT=6379
 
#服务端所处位置
EXEC=${INSTALL_PATH}/redis/bin/redis-server
 
#客户端位置
CLIEXEC=${INSTALL_PATH}/redis/bin/redis-cli
 
#redis的PID文件位置，需要修改
PIDFILE=${INSTALL_PATH}/redis/run/redis_${REDISPORT}.pid
 
#redis的配置文件位置，需将${REDISPORT}修改为文件名
CONF="${INSTALL_PATH}/redis/conf/redis.conf"
 
case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting Redis server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -p $REDISPORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for Redis to shutdown ..."
                    sleep 1
                done
                echo "Redis stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
}

args()
{
    usage="Usage: $0 (dfs|yarn|zk|kafka|spark|flink|hbase|start|stop)"
 
    if [ $# -lt 2 ]; then
        echo $usage
        exit 1
    fi

    case $1 in
	  dfs)
		dfs $2
		;;
	  yarn)
		yarn $2
		;;
	  spark)
		spark $2
		;;
	  zk)
		zk $2
		;;
	  flink)
		flink $2
		;;
	  hbase)
		hbase $2
		;;
	  kafka)
		kafka $2
		;;
	  kibana)
		kibana $2
		;;
	  es)
		elasticsearch $2
		;;
	  redis)
		redis $2
		;;
	  *)
		echo $usage
		;;
    esac
}
args $@

