#!/bin/bash
user_name=$(id -un)
if [ "$user_name" = "root" -o "$user_name" = "vagrant" ];then
    # 服务器的密码
    passwd="vagrant"
else
    passwd=$user_name
fi
install_ssh() {
    if [ ! -f ~/.ssh/id_rsa ];then
        expect -c "
            spawn ssh-keygen
            expect {
                \"Enter file in which to save the*\" { send \"\r\"; exp_continue}
                \"Overwrite*\" { send \"n\r\" ; exp_continue}
                \"Enter passphrase*\" { send \"\r\"; exp_continue}
                \"Enter same passphrase again:\" { send \"\r\" ; exp_continue}
            }";
    fi
    hostList=$(cat /etc/hosts|grep -vE localhost |grep hdp| awk '{print $2}')
    for ip in $hostList;do
        expect -c "
            set timeout 5;
            spawn ssh-copy-id -i ${ip};
            expect {
                \"*assword\" { send \"${passwd}\r\";exp_continue}
                \"yes/no\" { send \"yes\r\"; exp_continue }
                eof {exit 0;}
            }";
        echo "========主机IP为：${ip}免登录执行完成========"
    done
}
install_ssh