#!/bin/bash
login_name=`id -un`
install_ssh() {
local user=$1
[ ! -f /home/$user/.ssh/id_rsa.pub ] && ssh-keygen -t rsa -q -f /home/$user/.ssh/id_rsa -P ''

for ip in `cat /etc/hosts|grep -vE localhost | awk '{print $2}'`; do
    port="22"
    pass=$user
    echo "========正在提交主机IP为：${ip}免登录========"
    expect -c "
        set timeout 5;
        spawn ssh-copy-id -i /home/$user/.ssh/id_rsa.pub ${user}@${ip} -p ${port};
        expect {
            \"*assword\" { send \"${pass}\r\";exp_continue}
            \"yes/no\" { send \"yes\r\"; exp_continue }
            eof {exit 0;}
        }";
    echo "========主机IP为：${ip}免登录执行完成========"
done
}
install_root_ssh() {
[ ! -f /root/.ssh/id_rsa.pub ] && ssh-keygen -t rsa -q -f /root/.ssh/id_rsa -P ''

for ip in `cat /etc/hosts|grep -vE localhost | awk '{print $2}'`; do
    port="22"
    user="root"
    pass="vagrant"
    echo "========正在提交主机IP为：${ip}免登录========"
    expect -c "
        set timeout 5;
        spawn ssh-copy-id -i /root/.ssh/id_rsa.pub ${user}@${ip} -p ${port};
        expect {
            \"*assword\" { send \"${pass}\r\";exp_continue}
            \"yes/no\" { send \"yes\r\"; exp_continue }
            eof {exit 0;}
        }";
    echo "========主机IP为：${ip}免登录执行完成========"
done
}
if [ "$login_name" = "root" ];then
    install_root_ssh
else
    install_ssh $login_name
fi