#!/bin/bash

# 获取输出参数，如果没有参数则直接返回
pcount=$#
if [ $pcount -eq 0 ]
then
    echo "no parameter find !";
    exit;
fi

# 获取传输文件名
p1=$1
filename=`basename $p1`
echo "load file $p1 success !"

# 获取文件的绝对路径
pdir=`cd -P $(dirname $p1); pwd`
echo "file path is $pdir"

# 获取当前用户
user=`whoami`
#echo $user
# 拷贝文件到从机(这里注意主机的host需要根据你的实际情况配置，要与你具体的主机名对应)
#for (( host=1;host<=3;host++ ))
for host in hdp{101..103};
do 
    current_hostname=`cat /etc/hostname`
    if [ "$current_hostname" != "$host" ];then
        echo "================current host is $host================="
        rsync -rvl $pdir/$filename $user@$host:$pdir
    fi
done

echo "complate !"

