create database web;
use web;

create Table ip(
ip_start string comment 'Start IP',
ip_end string comment 'End IP',
location string comment 'Location',
isp string comment 'ISP information'
)
comment 'Ip address information table'
row format delimited fields terminated by '\t';

CREATE TABLE log(
id BIGINT comment 'LOG ID',
ip string comment 'User IP address',
access_time string comment 'Access time',
access_url string comment 'Access URL',
status INT comment 'Status code',
traffic BIGINT comment 'Traffic generated by the access',
source_url string comment 'Referrer URL'
)
comment 'Table to store web access logs'
row format delimited fields terminated by '\t';

load data inpath '/data/ip_processed.txt' into table ip;
load data inpath '/data/log_processed.txt' into table log;

create table ip_log_num(
type string,
num int
);

insert overwrite table ip_log_num
select 'log', count(*) as num from web.log where log.status='301'
union all
select 'ip', count(*) from web.ip where ip.location='IANA';

create table asses_url_top(
rank int,
access_url string,
times int
);

insert overwrite table asses_url_top
select
row_NUMBER() over (order by COUNT(*) desc ) as rank,
access_url,
COUNT(*) as times
from log
group by access_url
order by times desc
limit 10;
